<#
.SYNOPSIS
    One-shot installer for the D365 AxDB MCP server.

.DESCRIPTION
    Run this script once on a new machine to:
      1. Check prerequisites  (Python 3.11+, ODBC Driver 17)
      2. Create a local .venv inside the repo
      3. Install all Python dependencies  (mcp, pyodbc, python-dotenv, etc.)
      4. Create your personal .env with your Tier 1 DEV machine name
      5. Run a live connection test against your AxDB
      6. Confirm .vscode/mcp.json is in place

    After this script completes, open the repo in VS Code, switch Copilot Chat
    to Agent mode, and the D365 tools will be available for any value stream
    (HR, Finance, SCM, Projects, etc.).

.NOTES
    Requirements before running:
      - Git clone of this repo
      - Domain account with read access to your GNSPLC-DEV-### machine
      - Python 3.11 or later  (https://www.python.org/downloads/)
      - ODBC Driver 17 for SQL Server  (https://aka.ms/odbc17)

    Run with:
      Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      .\Install-D365MCP.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Helpers ──────────────────────────────────────────────────────────────────

function Write-Step { param([string]$Msg)  Write-Host "`n==> $Msg" -ForegroundColor Cyan }
function Write-OK   { param([string]$Msg)  Write-Host "    [OK] $Msg" -ForegroundColor Green }
function Write-Warn { param([string]$Msg)  Write-Host "    [!]  $Msg" -ForegroundColor Yellow }
function Write-Fail { param([string]$Msg)  Write-Host "    [FAIL] $Msg" -ForegroundColor Red; exit 1 }

$RepoRoot = $PSScriptRoot    # directory containing this script = repo root
$VenvDir  = Join-Path $RepoRoot '.venv'
$EnvFile  = Join-Path $RepoRoot '.env'

Write-Host "`nD365 AxDB MCP Server — Installer" -ForegroundColor Magenta
Write-Host "Repo root: $RepoRoot`n"


# ── Step 1: Python version check ─────────────────────────────────────────────

Write-Step "Checking Python version"

$PyCmd = $null
foreach ($cmd in @('python', 'python3', 'py')) {
    if (Get-Command $cmd -ErrorAction SilentlyContinue) {
        $ver = & $cmd --version 2>&1
        if ($ver -match '(\d+)\.(\d+)') {
            $major = [int]$Matches[1]; $minor = [int]$Matches[2]
            if ($major -ge 3 -and $minor -ge 11) {
                $PyCmd = $cmd
                Write-OK "$ver"
                break
            }
        }
    }
}

if (-not $PyCmd) {
    Write-Fail "Python 3.11+ not found. Download from https://www.python.org/downloads/ and re-run."
}


# ── Step 2: ODBC Driver check ─────────────────────────────────────────────────

Write-Step "Checking ODBC Driver 17 for SQL Server"

$odbc = Get-OdbcDriver -Name "ODBC Driver 17 for SQL Server" -Platform "64-bit" -ErrorAction SilentlyContinue
if ($odbc) {
    Write-OK "ODBC Driver 17 found"
} else {
    Write-Warn "ODBC Driver 17 NOT found."
    Write-Warn "Download from: https://aka.ms/odbc17"
    Write-Warn "Continuing install — connection test will fail until driver is installed."
}


# ── Step 3: Create virtual environment ───────────────────────────────────────

Write-Step "Creating Python virtual environment at .venv"

if (Test-Path $VenvDir) {
    Write-OK ".venv already exists — skipping creation"
} else {
    & $PyCmd -m venv $VenvDir
    Write-OK ".venv created"
}

$PipExe  = Join-Path $VenvDir 'Scripts\pip.exe'
$PyExe   = Join-Path $VenvDir 'Scripts\python.exe'


# ── Step 4: Install dependencies ──────────────────────────────────────────────

Write-Step "Installing Python dependencies"

& $PipExe install --upgrade pip --quiet
& $PipExe install -r (Join-Path $RepoRoot 'requirements.txt') --quiet
Write-OK "Dependencies installed"


# ── Step 5: Create .env ───────────────────────────────────────────────────────

Write-Step "Configuring your AxDB connection (.env)"

if (Test-Path $EnvFile) {
    Write-OK ".env already exists — skipping. Edit it manually if needed: $EnvFile"
} else {
    # Auto-detect: DEV machine is typically the local hostname
    $DefaultServer = $env:COMPUTERNAME

    Write-Host ""
    Write-Host "  Your Tier 1 DEV machine name (press Enter to use '$DefaultServer'):"
    $InputServer = Read-Host "  AXDB_SERVER"
    if ([string]::IsNullOrWhiteSpace($InputServer)) { $InputServer = $DefaultServer }

    Write-Host "  Database name (press Enter for 'AxDB'):"
    $InputDb = Read-Host "  AXDB_DATABASE"
    if ([string]::IsNullOrWhiteSpace($InputDb)) { $InputDb = "AxDB" }

    $EnvContent = @"
# D365 AxDB connection — auto-generated by Install-D365MCP.ps1
# Edit this file if your machine name or DB changes.
# DO NOT commit this file to Git.

AXDB_SERVER=$InputServer
AXDB_DATABASE=$InputDb
AXDB_DRIVER=ODBC Driver 17 for SQL Server
"@
    Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
    Write-OK ".env created: AXDB_SERVER=$InputServer  AXDB_DATABASE=$InputDb"
}


# ── Step 6: Connection test ───────────────────────────────────────────────────

Write-Step "Testing live AxDB connection"

$TestScript = Join-Path $RepoRoot 'tools\connection_test.py'
$TestOutput = & $PyExe $TestScript 2>&1

if ($LASTEXITCODE -eq 0) {
    foreach ($line in $TestOutput) { Write-OK $line }
} else {
    Write-Warn "Connection test failed:"
    foreach ($line in $TestOutput) { Write-Warn "  $line" }
    Write-Warn "Check your AXDB_SERVER value in .env and ensure you are on the domain."
    Write-Warn "Re-run .\Install-D365MCP.ps1 after fixing, or edit .env manually."
}


# ── Step 7: Confirm .vscode/mcp.json ──────────────────────────────────────────

Write-Step "Checking VS Code MCP registration"

$VscodeMcpPath = Join-Path $RepoRoot '.vscode\mcp.json'

if (Test-Path $VscodeMcpPath) {
    Write-OK ".vscode/mcp.json found — server registration is in place"
    Write-OK "VS Code will load your .env automatically via the envFile setting"
} else {
    Write-Warn ".vscode/mcp.json not found — pull the latest changes from main and re-run."
}


# ── Done ──────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "══════════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Open this repo folder in VS Code"
Write-Host "    2. Open Copilot Chat (Ctrl+Alt+I) -> switch to Agent mode"
Write-Host "    3. You should see D365 tools in the tool picker"
Write-Host "    4. Try: 'List all INVENT tables' or 'Show SQL for SALESORDERHEADERENTITY'"
Write-Host ""
Write-Host "  Your config: .env  (never commit this file)"
Write-Host "  To change server: edit AXDB_SERVER in .env"
Write-Host "══════════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host ""
